# Generated by Django 4.0.6 on 2022-07-20 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_alter_catalogue_img'),
    ]

    operations = [
        migrations.CreateModel(
            name='Updateprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pix', models.ImageField(default='default.jpg', upload_to='profiles')),
                ('address', models.CharField(max_length=50)),
                ('telephone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Updateprofile',
                'verbose_name_plural': 'Updateprofiles',
                'db_table': 'updateprofile',
                'managed': True,
            },
        ),
    ]
