# Generated by Django 4.0.6 on 2022-07-20 10:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_updateprofile'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Updateprofile',
            new_name='Profile',
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
