# Generated by Django 4.0.6 on 2022-07-20 21:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0005_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.CharField(max_length=50)),
                ('price', models.CharField(max_length=50)),
                ('serial_no', models.CharField(max_length=50)),
                ('paid', models.BooleanField(max_length=50)),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('catalogue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.catalogue')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
