# Generated by Django 4.0.6 on 2022-07-23 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_product_alter_shopcart_product_delete_catalogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meals',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='snacks',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='wines',
            field=models.BooleanField(default=False),
        ),
    ]
